#Лабораторна робота 1
###Студента групи МІТ-31 (підгрупа 2)
###Хоміка Богдана Сергійовича

##Завдання
1. NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Використати arange, random.
2. Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))
3. Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)

4. Відповіді оформити .ipynb документом
5. Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab1 де має бути .ipynb файл та необхідні файли з даними

In [7]:
import numpy as np

import matplotlib as mpl

print("CRUD : for numbers")
x = np.random.randint(0, 10)
y = np.random.randint(0, 10)
print("x = ", x)
print("y = ", y)
print("x+y = ", x+y)
print("x-y = ", x-y)
print("x*y = ", x*y)
print("x/y = ", x/y)

print()
print("CRUD : for array")
print("Creation: ")
array1 = np.arange(10,50,4)
print(array1) 
array2 = np.random.randint(0, 100, 10)
print(array2)
print("Add new element into array2: ")
some_numb = np.random.randint(0, 100)
print("Some_number = ", some_numb)
array2 = np.append(array2, some_numb)
print(array2)
print("")
print("Reading first element of second array:")
print(array2.item(0), end="\n\n")

print("Deleting: delete array2 last element")
array2 = np.delete(array2, -1)
print(array2, end="\n\n")

print("Changing array_1 last element to some_number")
array1[-1] = some_numb
print(array1, end="\n\n")

print("multiplication: ")
array1 = np.multiply(array1, 1.1)
print(array1)
print("elevation to the degree: ")
array2 = np.power(array2, 3)
print(array2, end="\n\n")

print("Vector multiplication: ")
first_array = np.add(array1,array2)
second_array = np.subtract(array1,array2)
print(first_array)
print(second_array, end="\n\n")

first_matrix = np.random.randint(10, 100, size = (4,4))
second_matrix = np.random.randint(10, 100, size = (4,4))
print("First_matrix: ")
print(first_matrix, sep="\n\n")
print("Matrix 2: ")
print(second_matrix, sep="\n\n")

print("SUM: ")
print(first_matrix+second_matrix)
print("DIFF: ")
print(first_matrix-second_matrix)
print("MULTi: ")
print(first_matrix*second_matrix)
print("DIVISION: ")
print(first_matrix/second_matrix)

CRUD : for numbers
x =  8
y =  9
x+y =  17
x-y =  -1
x*y =  72
x/y =  0.8888888888888888

CRUD : for array
Creation: 
[10 14 18 22 26 30 34 38 42 46]
[ 4 62 10 11 39  7 99 78 60 39]
Add new element into array2: 
Some_number =  86
[ 4 62 10 11 39  7 99 78 60 39 86]

Reading first element of second array:
4

Deleting: delete array2 last element
[ 4 62 10 11 39  7 99 78 60 39]

Changing array_1 last element to some_number
[10 14 18 22 26 30 34 38 42 86]

multiplication: 
[11.  15.4 19.8 24.2 28.6 33.  37.4 41.8 46.2 94.6]
elevation to the degree: 
[    64 238328   1000   1331  59319    343 970299 474552 216000  59319]

Vector multiplication: 
[7.500000e+01 2.383434e+05 1.019800e+03 1.355200e+03 5.934760e+04
 3.760000e+02 9.703364e+05 4.745938e+05 2.160462e+05 5.941360e+04]
[-5.300000e+01 -2.383126e+05 -9.802000e+02 -1.306800e+03 -5.929040e+04
 -3.100000e+02 -9.702616e+05 -4.745102e+05 -2.159538e+05 -5.922440e+04]

First_matrix: 
[[25 69 38 54]
 [65 68 38 24]
 [98 97 24 36]
 [24 75 19 34]]